source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftLightNum', :exclusive => true do
  pod "SwiftLightNum", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SwiftLightNum", :path => "../"

  
end
