//
//  LNStyle.h
//  SwiftLightNum
//
//  Created by Kevin Sullivan on 2/11/15.
//  Copyright (c) 2015 Ibex Inc. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>



@interface LNStyle : NSObject

// Shadows
+ (NSShadow*)shadowLarge;
+ (NSShadow*)shadowSmall;

// Drawing Methods
+ (void)drawLightNumButtonWithFrame: (CGRect)frame colorBackground: (UIColor*)colorBackground colorStroke: (UIColor*)colorStroke cornerRadius: (CGFloat)cornerRadius strokeWidth: (CGFloat)strokeWidth fontSize: (CGFloat)fontSize;

@end



@interface NSShadow (PaintCodeAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;
- (void)set;

@end
